/* The STC is a free running counter that increments at the rate of 1MHz */
#define STC_FREQ_HZ 1000000

/*
 * Constants generated by clocks_calc_mult_shift(m, s, 1MHz, NSEC_PER_SEC, 60).
 * This gives a resolution of about 1us and a wrap period of about 1h11min.
 */
#define SC_MULT		4194304000u
#define SC_SHIFT	22

static cycle_t stc_read_cycles(struct clocksource *cs)
{
	/* STC: a free running counter that increments at the rate of 1MHz */
	return (cycle_t) readl(__io_address(ST_BASE + 0x04));
}

static struct clocksource clocksource_stc = {
	.name = "stc",
	.rating = 300,
	.read = stc_read_cycles,
	.mask = CLOCKSOURCE_MASK(32),
	.flags = CLOCK_SOURCE_IS_CONTINUOUS,
};
